#!/usr/bin/env node

/**
 * Environment Setup Script
 * Interactive script to help set up .env file
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { createInterface } from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');

const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(query) {
  return new Promise(resolve => rl.question(query, resolve));
}

async function setupEnv() {
  console.log('🚀 Environment Variables Setup\n');
  console.log('This script will help you set up your .env file.');
  console.log('You can get your Supabase credentials from:');
  console.log('https://supabase.com/dashboard -> Your Project -> Settings -> API\n');

  const envPath = join(projectRoot, '.env');
  let envContent = '';

  // Check if .env already exists
  if (existsSync(envPath)) {
    const existing = readFileSync(envPath, 'utf-8');
    const urlMatch = existing.match(/^VITE_SUPABASE_URL=(.+)$/m);
    const keyMatch = existing.match(/^VITE_SUPABASE_PUBLISHABLE_KEY=(.+)$/m);
    
    if (urlMatch && keyMatch && urlMatch[1] && keyMatch[1].trim() !== '') {
      const overwrite = await question('⚠️  .env file already exists. Overwrite? (y/N): ');
      if (overwrite.toLowerCase() !== 'y') {
        console.log('✅ Keeping existing .env file');
        rl.close();
        return;
      }
    }
  }

  // Get Supabase URL
  console.log('\n📝 Enter your Supabase Project URL:');
  console.log('   (Example: https://xxxxx.supabase.co)');
  const supabaseUrl = await question('VITE_SUPABASE_URL: ');
  
  if (!supabaseUrl || !supabaseUrl.trim()) {
    console.error('❌ URL cannot be empty!');
    rl.close();
    process.exit(1);
  }

  // Get Supabase Key
  console.log('\n📝 Enter your Supabase anon/public key:');
  console.log('   (Get this from Settings -> API -> anon public)');
  const supabaseKey = await question('VITE_SUPABASE_PUBLISHABLE_KEY: ');
  
  if (!supabaseKey || !supabaseKey.trim()) {
    console.error('❌ Key cannot be empty!');
    rl.close();
    process.exit(1);
  }

  // Create .env content
  envContent = `# Supabase Configuration
# Generated by setup script

VITE_SUPABASE_URL=${supabaseUrl.trim()}
VITE_SUPABASE_PUBLISHABLE_KEY=${supabaseKey.trim()}
`;

  // Write .env file
  writeFileSync(envPath, envContent);
  console.log('\n✅ .env file created successfully!');
  console.log(`📁 Location: ${envPath}`);
  console.log('\n💡 Next steps:');
  console.log('1. Run: npm run dev');
  console.log('2. Check that the app loads without errors');
  console.log('3. Try logging in to verify Supabase connection');

  rl.close();
}

setupEnv().catch(err => {
  console.error('❌ Error:', err.message);
  rl.close();
  process.exit(1);
});

